name: CD

on:
  workflow_call:
    secrets:
      git_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Clone config repo
      uses: actions/checkout@v4
      with:
        repository: IVVORG/airs-config-sync
        ref: main
        token:  ${{ secrets.git_token }}
        path: airs-config-sync

    - name: Update swarm-sync config repo
      run: |
        chmod +x ./.github/scripts/update-config-rc.sh
        bash ./.github/scripts/update-config-rc.sh
