name: Go
on: 
  push:
    paths-ignore:
      - '.github/**' 

jobs:
  
  analisys:
    name: Analisys
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v43

    - name: Define if rc needed
      id: date
      run: |
        for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
          if [ $file = 'ModifyForDeploy.Me' ]; then
            echo "need=true" >> $GITHUB_OUTPUT
            exit 0
          fi   
        done        

  call-workflow-cd:
    if ${{ steps.date.outputs.date }} == 'true' 
    uses: ./.github/workflows/cd.yml 
    secrets:
      git_token: ${{ secrets.REPOREADING_TOKEN }}

